version: "3.8"

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: app
  #   container_name: app
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - '$PORT:$PORT'
  #   depends_on:
  #     - mongodb
  #     - redis

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    env_file: .env
    ports:
      - '$REDIS_PORT:$REDIS_PORT'
    volumes:
      - redis_data:/data/cache

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  redis_data:
